use movies

/*task 1*/
SELECT ADDRESS FROM STUDIO WHERE STUDIO.NAME = 'Disney'

/*Task 2*/
SELECT BIRTHDATE FROM MOVIESTAR WHERE MOVIESTAR.NAME = 'Jack Nicholson'

/*Task 3*/
SELECT STARNAME FROM STARSIN, MOVIE 
WHERE (MOVIE.YEAR = 1980 OR MOVIE.TITLE LIKE '%Knight%') AND MOVIE.TITLE = STARSIN.MOVIETITLE

/*Task 4*/
SELECT NAME FROM MOVIEEXEC WHERE MOVIEEXEC.NETWORTH >= 10000000

/*Task 5*/
SELECT NAME FROM MOVIESTAR WHERE MOVIESTAR.GENDER = 'M' OR MOVIESTAR.ADDRESS = 'Prefect Rd'
